### ISSUE TITLE
Feature: Allow Elements in `list` Constructor of `Message` Being `str`

### ISSUE THREAD

**Issue by src-hyc** [nonebot/nonebot2#1793]
I was trying to compose a `Message` (in `nonebot.adapters.onebot.v11`) object, but encountered some problems.

At first, I tried the following code:

```py
Message('Example message')
```

It returned a `Message` object, with text "Example message," just as expected.

Later on, I decided to have the bot at me in the IM software, so I updated the code to be:

```py
Message(['Example message', MessageSegment.at(42)])
```

Let us pretend that my id is 42 in the IM software. Surprisingly, the code failed on linting, as there is only list[TMS] constructor for `Message`.

The problem is actually easily solvable by simply making `'Example message'` into `MessageSegment.text('Example message')`, or to be more clear, like:

```py
Message([MessageSegment.text('Example message'), MessageSegment.at(42)])
```

However, I am not satisfied by the solution, as `Message(MessageSegment.text('Example message'))` and `Message('Example message')` are equal to each other, but `Message(['Example message', MessageSegment.at(42)])` cannot even pass the linter.

Moreover, if I just turn a blind eye to the linter and run the code anyway, `Message(['Example message', MessageSegment.at(42)])` and `Message([MessageSegment.text('Example message'), MessageSegment.at(42)])` are equal to each other as well!

Please let me know if there is a unseen problem preventing me from construct `Message` with `['Example message', MessageSegment.at(42)]`, otherwise I recognize this as a typing mistake. It would be good and unarguably increase the quality of my life to make it pass the linter.

**Comment by yanyongyu** [comment]
Hi, the problem I want to point out here is that  
Although the code can be run, this is a non-recommended way. The code may be more confusing to developer. Some reasons:

First, `Message("some text here")` is not equal to `Message(MessageSegment.text("some text here"))`.  
Passing a raw string to `Message` class will make the adapter to **construct** the text into a list of `MessageSegment`s. Here's an example for onebot v11:

```python
Message("[cq:at,qq=123123]") == Message([MessageSegment.at(123123)])
```

As you can see, raw string input will be convert to structured segments. So, passing a string to `Message` class is calling parsing action.

Back to your code, `Message(["some text here", MessageSegment.at(123123)])` is also not equal to `Message([MessageSegment.text("some text here"), MessageSegment.at(123123)])`, because of the action of parser constructing.

But why type hint does not allow this behavior? As the code you provided, passing a string in list is **confusing**! The actual behavior is not consistent with what you think. So, we limited the `Message` class type hints to ensure that user will not writing such confusing code.

Finally, some recommended way:

1. Write every segment type. This will prevent unexpected behavior.
   ```python
   MessageSegment.text("some text here") + MessageSegment.at(123123)
   ```
2. Construct separately.
   ```python
   Message("some text here") + MessageSegment.at(123123)
   ```
3. In onebot adapter **only**, for security reason, string will not cause construct if used in binary operator.
   ```python
   "some text here" + MessageSegment.at(123123)
   ```
